# https://docs.travis-ci.com/user/languages/go
language: go
sudo: false

# https://cloud.google.com/appengine/docs/go/release-notes
# the golang version should match the version in the pkg
go:
- "1.10"
script:
- go build .
notifications:
  email:
    on_success: never
    on_failure: change
