# https://docs.travis-ci.com/user/languages/go
language: go
sudo: false
go:
  - "1.10"
before_script:
  - go get github.com/golang/lint/golint
script:
  - go vet ./...
  - golint
  - go build .
notifications:
  email:
    on_success: never
    on_failure: change
