# https://docs.travis-ci.com/user/languages/go
language: go
sudo: false
go:
  - "1.11"
env:
  - GO111MODULE=on
before_script:
  - go get github.com/golang/lint/golint
script:
  - go vet ./...
  - golint
  - go build .
notifications:
  email:
    on_success: change
    on_failure: change
