version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://nat@docker.for.mac.localhost/writing?sslmode=disable
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
